title: Welcome to
email: p.knittl.frank@gmail.com
baseurl: "/FurnitAR" # the subpath of your site, e.g. /blog
url: "https://barokai.github.io" # the base hostname & protocol for your site, e.g. http://example.com
domain: "barokai.github.io"
twitter_username: barokai
github_username: barokai

logo: /assets/images/logo.png
show_downloads: true
favicon: true

# custom settings (for cloudflare build - currently disabled)
repository: Barokai/FurnitAR

github:
  zip_url: https://1drv.ms/u/s!AufoJNRhqarVpJN1GxdemRS7c-ln1w?e=00xRj1
  docu: /FurnitAR/assets/FurnitAR_documentation_Knittl_Frank_Peter.pdf
  targets: /FurnitAR/assets/ImageTargets.pdf
  apk: https://github.com/Barokai/FurnitAR/releases/download/v0.3-abgabe/FurnitAR.apk
  screenshots: /FurnitAR/assets/FurnitAR_screenshots.zip
  screenshot1: /FurnitAR/assets/FurnitAR_screenshot1.png
  screenshot2: /FurnitAR/assets/FurnitAR_screenshot2.png
  screenshot3: /FurnitAR/assets/FurnitAR_screenshot3.png
  slides: /FurnitAR/slides/index.html

color-scheme: "auto-default-dark"
remote_theme: "godalming123/minimal"
#remote_theme: pages-themes/minimal@v0.2.0

plugins:
- jekyll-remote-theme