# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: FurnitAR
email: p.knittl.frank@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Augmented reality aids people with visual effects that relate to
the environment of the space and with this concept people can
view the furniture in the room without actually moving or placing
physical objects in the area. The users interactively chooses material
and furniture model and places it in the room without needed to
do this manually with a real piece of furniture. This interactive
process enables the user to check how a piece of furniture looks in
the room, also with different materials used as the models texture.
A system has been developed which allows to choose and rotate
models for preview, change the material and place the model textured
with the chosen material in life-size on the ground. Thus, the user
can experience different furniture arrangements and share his/her
creations via the application
baseurl: "/FurnitAR" # the subpath of your site, e.g. /blog
url: "https://barokai.github.io" # the base hostname & protocol for your site, e.g. http://example.com
domain: "barokai.github.io"
twitter_username: barokai
github_username:  barokai

logo: /assets/images/logo.png
show_downloads: true

favicon: true

# custom settings (for cloudflare build)
repository: Barokai/FurnitAR


github:
  zip_url: /assets/FurnitAR.zip
  docu: /assets/FurnitAR_documentation_Knittl_Frank_Peter.pdf
  targets: /assets/ImageTargets.pdf
  apk: /assets/FurnitAR.apk
  screenshot1: /assets/FurnitAR_screenshot1.jpg
  screenshot2: /assets/FurnitAR_screenshot2.jpg
  slides: /assets/slides/index.html

# Build settings
# theme: minima
# plugins:
#   - jekyll-feed

#remote_theme: pages-themes/minimal@v0.2.0

color-scheme: "auto-default-dark"
remote_theme: "godalming123/minimal"
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# theme: jekyll-theme-minimal